### PR TITLE
[Feature from LNSSPsd]轻量化lua插件支持

### PR DESCRIPTION
**Pull request by RainyHallways**

### CODE REVIEW

**Comment by RainyHallways** [comment]
Do not merge this pr until it was reviewed by @awaqwqa

**Comment by VitaElegy** [comment]
欸woc怎么在这边来额

**Comment by VitaElegy** [comment]
怎么这边也有（

**Comment by RainyHallways** [comment]
(

**Comment by RainyHallways** [comment]
resync

**Pull request closed without merging**
